name: Deploy ML API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Python
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: '3.9'
    #
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # pip install pytest

    - name: Build Docker image
      run: |
        docker build -t california-housing-prices .

    - name: Deploy to Cloud Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # docker stop house-api || true
          # docker rm house-api || true
          # docker run -d --name house-api -p 80:80 california-housing-prices
          docker run -p 80:80 california-housing-prices

